[package]
name = "brink-codegen-json"
description = "JSON codegen backend: LIR → ink.json format"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
brink-ir = { workspace = true }
brink-format = { workspace = true }
brink-json = { workspace = true }

[lints]
workspace = true
