//! Typed AST wrappers for the ink CST.
//!
//! Every struct is a zero-cost newtype around [`SyntaxNode`] that implements
//! [`AstNode`]. Use [`crate::Parse::tree()`] to get a [`SourceFile`] from
//! a parse result.

mod nodes;
mod support;

pub use nodes::*;

use crate::SyntaxNode;

/// A typed wrapper around a [`SyntaxNode`].
///
/// Implementations are generated by the [`ast_node!`] macro.
pub trait AstNode: Sized {
    /// Returns `true` if a node with the given kind can be cast to `Self`.
    fn can_cast(kind: crate::SyntaxKind) -> bool;

    /// Try to cast a generic `SyntaxNode` into this typed wrapper.
    fn cast(node: SyntaxNode) -> Option<Self>;

    /// Access the underlying `SyntaxNode`.
    fn syntax(&self) -> &SyntaxNode;
}

/// Generates a zero-cost newtype struct implementing [`AstNode`].
///
/// ```ignore
/// ast_node!(SourceFile, SOURCE_FILE);
/// ```
///
/// expands to a struct wrapping `SyntaxNode` with `AstNode`, `Debug`,
/// `Clone`, `PartialEq`, `Eq`, and `Hash` implementations.
macro_rules! ast_node {
    ($name:ident, $kind:ident) => {
        #[derive(Clone, PartialEq, Eq, Hash)]
        pub struct $name {
            syntax: $crate::SyntaxNode,
        }

        impl std::fmt::Debug for $name {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                std::fmt::Debug::fmt(&self.syntax, f)
            }
        }

        impl $crate::ast::AstNode for $name {
            fn can_cast(kind: $crate::SyntaxKind) -> bool {
                kind == $crate::SyntaxKind::$kind
            }

            fn cast(node: $crate::SyntaxNode) -> Option<Self> {
                if Self::can_cast(node.kind()) {
                    Some(Self { syntax: node })
                } else {
                    None
                }
            }

            fn syntax(&self) -> &$crate::SyntaxNode {
                &self.syntax
            }
        }
    };
}

pub(crate) use ast_node;

#[cfg(test)]
mod tests {
    use super::*;

    /// Recursively find the first descendant node that casts to `N`.
    fn find_descendant<N: AstNode>(node: &crate::SyntaxNode) -> Option<N> {
        for child in node.children() {
            if let Some(n) = N::cast(child.clone()) {
                return Some(n);
            }
            if let Some(n) = find_descendant::<N>(&child) {
                return Some(n);
            }
        }
        None
    }

    // ── Parse::tree() ────────────────────────────────────────────────

    #[test]
    fn source_file_cast_empty() {
        let parse = crate::parse("");
        let sf = SourceFile::cast(parse.syntax());
        assert!(sf.is_some());
    }

    #[test]
    fn source_file_cast_wrong_kind() {
        let parse = crate::parse("Hello\n");
        let root = parse.syntax();
        let first_child = root.children().next();
        assert!(first_child.is_some());
        let child = first_child.unwrap();
        assert!(SourceFile::cast(child).is_none());
    }

    #[test]
    fn parse_tree_roundtrip() {
        let src = "Hello world\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        assert_eq!(tree.syntax().text().to_string(), src);
    }

    #[test]
    fn parse_tree_with_knot() {
        let src = "=== myKnot ===\nSome content\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        assert_eq!(tree.knots().count(), 1);
    }

    // ── Named declarations ───────────────────────────────────────────

    #[test]
    fn knot_header_name() {
        let src = "=== myKnot ===\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let knot = tree.knots().next().unwrap();
        let header = knot.header().unwrap();
        assert_eq!(header.name().as_deref(), Some("myKnot"));
        assert!(!header.is_function());
    }

    #[test]
    fn function_knot_header() {
        let src = "== function greet(ref name) ==\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let knot = tree.knots().next().unwrap();
        let header = knot.header().unwrap();
        assert!(header.is_function());
        assert_eq!(header.name().as_deref(), Some("greet"));
        let params = header.params().unwrap();
        let param = params.params().next().unwrap();
        assert!(param.is_ref());
        assert_eq!(param.name().as_deref(), Some("name"));
    }

    #[test]
    fn stitch_header_name() {
        let src = "=== myKnot ===\n= myStitch\nContent\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let knot = tree.knots().next().unwrap();
        let body = knot.body().unwrap();
        let stitch = body.stitches().next().unwrap();
        let header = stitch.header().unwrap();
        assert_eq!(header.name().as_deref(), Some("myStitch"));
    }

    #[test]
    fn var_decl_name() {
        let src = "VAR x = 5\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.var_decls().next().unwrap();
        assert_eq!(decl.name().as_deref(), Some("x"));
    }

    #[test]
    fn const_decl_name() {
        let src = "CONST pi = 3\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.const_decls().next().unwrap();
        assert_eq!(decl.name().as_deref(), Some("pi"));
    }

    #[test]
    fn list_decl_name() {
        let src = "LIST items = sword, shield\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.list_decls().next().unwrap();
        assert_eq!(decl.name().as_deref(), Some("items"));
    }

    #[test]
    fn temp_decl_name() {
        let src = "=== k ===\n~ temp x = 1\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let knot = tree.knots().next().unwrap();
        let body = knot.body().unwrap();
        let logic = body.logic_lines().next().unwrap();
        let temp = logic.temp_decl().unwrap();
        assert_eq!(temp.name().as_deref(), Some("x"));
    }

    #[test]
    fn external_decl_name() {
        let src = "EXTERNAL greet(a, b)\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let ext = tree.externals().next().unwrap();
        assert_eq!(ext.name().as_deref(), Some("greet"));
        let params = ext.param_list().unwrap();
        let names: Vec<_> = params.params().filter_map(|id| id.name()).collect();
        assert_eq!(names, vec!["a", "b"]);
    }

    // ── Path ─────────────────────────────────────────────────────────

    #[test]
    fn path_segments_simple() {
        let src = "-> target\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let content = tree.content_lines().next().unwrap();
        let divert = content.divert().unwrap();
        let simple = divert.simple_divert().unwrap();
        let target = simple.targets().next().unwrap();
        let path = target.path().unwrap();
        assert_eq!(path.full_name(), "target");
        assert_eq!(path.segments().count(), 1);
    }

    #[test]
    fn path_segments_dotted() {
        let src = "-> knot.stitch\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let content = tree.content_lines().next().unwrap();
        let divert = content.divert().unwrap();
        let simple = divert.simple_divert().unwrap();
        let target = simple.targets().next().unwrap();
        let path = target.path().unwrap();
        assert_eq!(path.full_name(), "knot.stitch");
        assert_eq!(path.segments().count(), 2);
    }

    // ── SimpleDivert / DivertNode ────────────────────────────────────

    #[test]
    fn simple_divert_target() {
        let src = "-> myKnot\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let content = tree.content_lines().next().unwrap();
        let divert = content.divert().unwrap();
        let simple = divert.simple_divert().unwrap();
        assert_eq!(simple.targets().count(), 1);
    }

    #[test]
    fn divert_to_done() {
        let src = "-> DONE\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let content = tree.content_lines().next().unwrap();
        let divert = content.divert().unwrap();
        let simple = divert.simple_divert().unwrap();
        let target = simple.targets().next().unwrap();
        assert!(target.done_kw().is_some());
        assert!(target.path().is_none());
    }

    #[test]
    fn divert_to_end() {
        let src = "-> END\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let content = tree.content_lines().next().unwrap();
        let divert = content.divert().unwrap();
        let simple = divert.simple_divert().unwrap();
        let target = simple.targets().next().unwrap();
        assert!(target.end_kw().is_some());
    }

    // ── FunctionCall ─────────────────────────────────────────────────

    #[test]
    fn function_call_name() {
        let src = "=== k ===\n~ temp x = foo(1, 2)\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let knot = tree.knots().next().unwrap();
        let body = knot.body().unwrap();
        let logic = body.logic_lines().next().unwrap();
        let temp = logic.temp_decl().unwrap();
        let fc = find_descendant::<FunctionCall>(temp.syntax()).unwrap();
        assert_eq!(fc.name().as_deref(), Some("foo"));
        assert_eq!(fc.arg_list().unwrap().arg_count(), 2);
    }

    // ── Literals ─────────────────────────────────────────────────────

    #[test]
    fn integer_lit_value() {
        let src = "VAR x = 42\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.var_decls().next().unwrap();
        let lit = find_descendant::<IntegerLit>(decl.syntax()).unwrap();
        assert_eq!(lit.value(), Some(42));
    }

    #[test]
    fn float_lit_value() {
        let src = "VAR x = 2.5\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.var_decls().next().unwrap();
        let lit = find_descendant::<FloatLit>(decl.syntax()).unwrap();
        assert_eq!(lit.value(), Some(2.5));
    }

    #[test]
    fn boolean_lit_true() {
        let src = "VAR x = true\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.var_decls().next().unwrap();
        let lit = find_descendant::<BooleanLit>(decl.syntax()).unwrap();
        assert_eq!(lit.value(), Some(true));
    }

    #[test]
    fn boolean_lit_false() {
        let src = "VAR x = false\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.var_decls().next().unwrap();
        let lit = find_descendant::<BooleanLit>(decl.syntax()).unwrap();
        assert_eq!(lit.value(), Some(false));
    }

    // ── ChoiceBullets ────────────────────────────────────────────────

    #[test]
    fn choice_bullets_depth_and_sticky() {
        let src = "* Choice one\n";
        let parse = crate::parse(src);
        let choice = find_descendant::<Choice>(parse.tree().syntax()).unwrap();
        let bullets = choice.bullets().unwrap();
        assert_eq!(bullets.depth(), 1);
        assert!(!bullets.is_sticky());
    }

    #[test]
    fn choice_bullets_sticky() {
        let src = "+ Sticky choice\n";
        let parse = crate::parse(src);
        let choice = find_descendant::<Choice>(parse.tree().syntax()).unwrap();
        let bullets = choice.bullets().unwrap();
        assert_eq!(bullets.depth(), 1);
        assert!(bullets.is_sticky());
    }

    #[test]
    fn choice_bullets_nested() {
        let src = "** Nested\n";
        let parse = crate::parse(src);
        let choice = find_descendant::<Choice>(parse.tree().syntax()).unwrap();
        let bullets = choice.bullets().unwrap();
        assert_eq!(bullets.depth(), 2);
    }

    // ── Label ────────────────────────────────────────────────────────

    #[test]
    fn choice_label_name() {
        let src = "* (myLabel) Choice text\n";
        let parse = crate::parse(src);
        let choice = find_descendant::<Choice>(parse.tree().syntax()).unwrap();
        let label = choice.label().unwrap();
        assert_eq!(label.name().as_deref(), Some("myLabel"));
    }

    #[test]
    fn gather_label_name() {
        let src = "- (end) The end\n";
        let parse = crate::parse(src);
        let gather = find_descendant::<Gather>(parse.tree().syntax()).unwrap();
        let label = gather.label().unwrap();
        assert_eq!(label.name().as_deref(), Some("end"));
    }

    // ── Tags ─────────────────────────────────────────────────────────

    #[test]
    fn content_line_tags() {
        let src = "Hello #tag1 #tag2\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let line = tree.content_lines().next().unwrap();
        let tags = line.tags().unwrap();
        let values: Vec<_> = tags.tags().map(|t| t.text()).collect();
        assert_eq!(values, vec!["tag1", "tag2"]);
    }

    // ── GatherDashes ─────────────────────────────────────────────────

    #[test]
    fn gather_dashes_depth() {
        let src = "-- deeper\n";
        let parse = crate::parse(src);
        let gather = find_descendant::<Gather>(parse.tree().syntax()).unwrap();
        let dashes = gather.dashes().unwrap();
        assert_eq!(dashes.depth(), 2);
    }

    // ── Identifier ───────────────────────────────────────────────────

    #[test]
    fn identifier_name() {
        let src = "VAR myVar = 1\n";
        let parse = crate::parse(src);
        let tree = parse.tree();
        let decl = tree.var_decls().next().unwrap();
        let ident = decl.identifier().unwrap();
        assert_eq!(ident.name().as_deref(), Some("myVar"));
        assert!(ident.ident_token().is_some());
    }
}
