[package]
name = "brink-intl"
description = "Internationalization tooling for brink stories"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
brink-format = { workspace = true }
icu_locale_core = { workspace = true }
icu_plurals = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
xliff2 = { workspace = true, features = ["metadata"] }

[dev-dependencies]
brink-compiler = { path = "../../brink-compiler" }
brink-runtime = { path = "../../brink-runtime" }
insta = { workspace = true, features = ["json"] }
serde_json = { workspace = true }

[lints]
workspace = true
