[package]
name = "brink-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Runtime/VM for executing compiled ink stories"

[package.metadata.docs.rs]
all-features = true

[dependencies]
brink-format = { workspace = true }
serde = { workspace = true }
thiserror.workspace = true

[features]
testing = []

[dev-dependencies]
brink-compiler = { path = "../brink-compiler" }
brink-converter = { path = "../internal/brink-converter" }
brink-json = { path = "../internal/brink-json" }
serde_json.workspace = true
divan.workspace = true

[[bench]]
name = "runtime"
harness = false

[lints]
workspace = true
