//! Oracle episode types and comparison logic.
//!
//! Oracle episodes are generated by the C# ink runtime (tools/ink-oracle).
//! Each step corresponds to one `Continue()` call. Variables and container
//! paths use string names. This module handles loading and comparing against
//! brink's `continue_single()` output.

use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use serde_json::Value as JsonValue;

// ---------------------------------------------------------------------------
// Oracle episode types (deserialized from .oracle.json)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub struct OracleEpisode {
    pub steps: Vec<OracleStep>,
    pub outcome: OracleOutcome,
    pub choice_path: Vec<usize>,
    pub initial_state: OracleInitialState,
}

/// A single step: one `Continue()` call's output.
#[derive(Debug, Deserialize)]
pub struct OracleStep {
    pub text: String,
    pub tags: Vec<String>,
    pub outcome: OracleStepOutcome,
    pub variable_changes: HashMap<String, JsonValue>,
    pub visit_changes: HashMap<String, i64>,
    pub turn_index: i64,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum OracleStepOutcome {
    Terminal(String), // "Continue", "Done", "Ended"
    Choices {
        #[serde(rename = "Choices")]
        choices: OracleChoicesData,
    },
}

#[derive(Debug, Deserialize)]
pub struct OracleChoicesData {
    pub presented: Vec<OracleChoiceRecord>,
    pub selected: usize,
}

#[derive(Debug, Deserialize)]
pub struct OracleChoiceRecord {
    pub text: String,
    pub index: usize,
    pub tags: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum OracleOutcome {
    Terminal(String),
    InputsExhausted {
        #[serde(rename = "InputsExhausted")]
        data: OracleInputsExhausted,
    },
    Error {
        #[serde(rename = "Error")]
        error: String,
    },
}

#[derive(Debug, Deserialize)]
pub struct OracleInputsExhausted {
    pub remaining_choices: Vec<OracleChoiceRecord>,
}

#[derive(Debug, Deserialize)]
pub struct OracleInitialState {
    pub variables: HashMap<String, JsonValue>,
    pub turn_index: i64,
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/// Load oracle episode files from a test case's `oracle/` directory.
pub fn load_oracle_episodes(case_dir: &Path) -> Result<Vec<OracleEpisode>, String> {
    let oracle_dir = case_dir.join("oracle");
    if !oracle_dir.is_dir() {
        return Err(format!("no oracle/ directory in {}", case_dir.display()));
    }

    let mut paths: Vec<PathBuf> = std::fs::read_dir(&oracle_dir)
        .map_err(|e| format!("read oracle dir: {e}"))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| e == "json")
                && p.to_string_lossy().contains(".oracle.")
        })
        .collect();
    paths.sort();

    let mut episodes = Vec::with_capacity(paths.len());
    for path in &paths {
        let content =
            std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let ep: OracleEpisode =
            serde_json::from_str(&content).map_err(|e| format!("parse {}: {e}", path.display()))?;
        episodes.push(ep);
    }

    Ok(episodes)
}

// ---------------------------------------------------------------------------
// Comparison
// ---------------------------------------------------------------------------

/// Result of comparing an oracle episode against a brink episode.
#[derive(Debug)]
pub struct OracleDiff {
    pub matches: bool,
    pub step_diffs: Vec<OracleStepDiff>,
    pub outcome_matches: bool,
}

#[derive(Debug)]
pub enum OracleStepDiff {
    Match,
    TextMismatch { expected: String, actual: String },
    TagsMismatch { expected: String, actual: String },
    OutcomeMismatch { expected: String, actual: String },
    MissingStep { expected_text: String },
    ExtraStep { actual_text: String },
}

impl fmt::Display for OracleDiff {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.matches {
            return write!(f, "episodes match");
        }
        writeln!(f, "oracle mismatch:")?;
        for (i, step_diff) in self.step_diffs.iter().enumerate() {
            match step_diff {
                OracleStepDiff::Match => {}
                OracleStepDiff::TextMismatch { expected, actual } => {
                    writeln!(f, "  step {i}: text differs")?;
                    writeln!(f, "    oracle:   {expected:?}")?;
                    writeln!(f, "    brink:    {actual:?}")?;
                }
                OracleStepDiff::TagsMismatch { expected, actual } => {
                    writeln!(f, "  step {i}: tags differ")?;
                    writeln!(f, "    oracle:   {expected}")?;
                    writeln!(f, "    brink:    {actual}")?;
                }
                OracleStepDiff::OutcomeMismatch { expected, actual } => {
                    writeln!(f, "  step {i}: outcome differs")?;
                    writeln!(f, "    oracle:   {expected}")?;
                    writeln!(f, "    brink:    {actual}")?;
                }
                OracleStepDiff::MissingStep { expected_text } => {
                    writeln!(
                        f,
                        "  step {i}: missing in brink (oracle: {expected_text:?})"
                    )?;
                }
                OracleStepDiff::ExtraStep { actual_text } => {
                    writeln!(f, "  step {i}: extra in brink ({actual_text:?})")?;
                }
            }
        }
        if !self.outcome_matches {
            writeln!(f, "  episode outcome differs")?;
        }
        Ok(())
    }
}

/// Compare an oracle episode against a brink episode.
///
/// Oracle steps are per-`Continue()` call. Brink steps are per-`continue_single()`.
/// We compare them in lockstep: text and tags per step, plus choice outcomes.
/// Done/Ended distinction is normalized.
pub fn diff_oracle(oracle: &OracleEpisode, brink: &crate::episode::Episode) -> OracleDiff {
    // Flatten brink's steps into per-line entries for comparison.
    // Each brink Line maps to one oracle Continue() step.
    let brink_lines = flatten_brink_episode(brink);

    let max_len = oracle.steps.len().max(brink_lines.len());
    let mut step_diffs = Vec::with_capacity(max_len);
    let mut all_match = true;

    for i in 0..max_len {
        match (oracle.steps.get(i), brink_lines.get(i)) {
            (Some(o), Some(b)) => {
                let d = compare_step(o, b);
                if !matches!(d, OracleStepDiff::Match) {
                    all_match = false;
                }
                step_diffs.push(d);
            }
            (Some(o), None) => {
                all_match = false;
                step_diffs.push(OracleStepDiff::MissingStep {
                    expected_text: o.text.clone(),
                });
            }
            (None, Some(b)) => {
                all_match = false;
                step_diffs.push(OracleStepDiff::ExtraStep {
                    actual_text: b.text.clone(),
                });
            }
            (None, None) => break,
        }
    }

    let outcome_matches = oracle_outcome_eq(&oracle.outcome, &brink.outcome);
    if !outcome_matches {
        all_match = false;
    }

    OracleDiff {
        matches: all_match,
        step_diffs,
        outcome_matches,
    }
}

/// A flattened brink line for comparison against oracle steps.
struct BrinkLine {
    text: String,
    tags: Vec<String>,
    outcome: BrinkLineOutcome,
}

enum BrinkLineOutcome {
    Continue,
    Done,
    Ended,
    Choices {
        presented: Vec<crate::episode::ChoiceRecord>,
        selected: usize,
    },
}

/// Flatten a brink episode into per-line entries.
///
/// Each brink `StepRecord` (from `continue_maximally`) contains potentially
/// multiple lines. We split on the `Line` boundaries: each line in the text
/// (delimited by `\n`) corresponds to one `Continue()` call.
///
/// However, brink's episode format stores accumulated text per
/// `continue_maximally` call, not per line. We need to split it back.
fn flatten_brink_episode(episode: &crate::episode::Episode) -> Vec<BrinkLine> {
    use crate::episode::StepOutcome;

    let mut lines = Vec::new();

    for (step_idx, step) in episode.steps.iter().enumerate() {
        let is_last_step = step_idx == episode.steps.len() - 1;

        // Split accumulated text into per-Continue() lines.
        // Each Continue() call produces text ending with \n (usually).
        let text_lines = split_into_continue_lines(&step.text);

        for (line_idx, line_text) in text_lines.iter().enumerate() {
            let is_last_line = line_idx == text_lines.len() - 1;

            // Tags: step.tags is per-text-line. Map to per-Continue() line.
            let tags = if line_idx < step.tags.len() {
                step.tags[line_idx].clone()
            } else {
                Vec::new()
            };

            let outcome = if is_last_line {
                match &step.outcome {
                    StepOutcome::Done => {
                        if is_last_step {
                            BrinkLineOutcome::Done
                        } else {
                            BrinkLineOutcome::Continue
                        }
                    }
                    StepOutcome::Ended => BrinkLineOutcome::Ended,
                    StepOutcome::Choices {
                        presented,
                        selected,
                    } => BrinkLineOutcome::Choices {
                        presented: presented.clone(),
                        selected: *selected,
                    },
                }
            } else {
                BrinkLineOutcome::Continue
            };

            lines.push(BrinkLine {
                text: line_text.clone(),
                tags,
                outcome,
            });
        }

        // If text was empty (e.g. choices with no preceding content),
        // still emit a line for the outcome.
        if text_lines.is_empty() {
            let outcome = match &step.outcome {
                StepOutcome::Done => BrinkLineOutcome::Done,
                StepOutcome::Ended => BrinkLineOutcome::Ended,
                StepOutcome::Choices {
                    presented,
                    selected,
                } => BrinkLineOutcome::Choices {
                    presented: presented.clone(),
                    selected: *selected,
                },
            };
            lines.push(BrinkLine {
                text: String::new(),
                tags: Vec::new(),
                outcome,
            });
        }
    }

    lines
}

/// Split accumulated text into per-`Continue()` call chunks.
/// Each `Continue()` typically produces text ending with `\n`.
fn split_into_continue_lines(text: &str) -> Vec<String> {
    if text.is_empty() {
        return Vec::new();
    }

    let mut result = Vec::new();
    let mut remaining = text;

    while let Some(newline_pos) = remaining.find('\n') {
        result.push(remaining[..=newline_pos].to_string());
        remaining = &remaining[newline_pos + 1..];
    }

    // If there's remaining text without a trailing newline, include it.
    if !remaining.is_empty() {
        result.push(remaining.to_string());
    }

    result
}

fn compare_step(oracle: &OracleStep, brink: &BrinkLine) -> OracleStepDiff {
    if oracle.text != brink.text {
        return OracleStepDiff::TextMismatch {
            expected: oracle.text.clone(),
            actual: brink.text.clone(),
        };
    }

    if oracle.tags != brink.tags {
        return OracleStepDiff::TagsMismatch {
            expected: format!("{:?}", oracle.tags),
            actual: format!("{:?}", brink.tags),
        };
    }

    if !step_outcome_eq(&oracle.outcome, &brink.outcome) {
        return OracleStepDiff::OutcomeMismatch {
            expected: format!("{:?}", oracle.outcome),
            actual: format_brink_outcome(&brink.outcome),
        };
    }

    OracleStepDiff::Match
}

fn step_outcome_eq(oracle: &OracleStepOutcome, brink: &BrinkLineOutcome) -> bool {
    match (oracle, brink) {
        (OracleStepOutcome::Terminal(s), BrinkLineOutcome::Continue) if s == "Continue" => true,
        // Normalize Done/Ended — both are terminal, C# doesn't reliably distinguish.
        (OracleStepOutcome::Terminal(s), BrinkLineOutcome::Done | BrinkLineOutcome::Ended)
            if s == "Done" || s == "Ended" =>
        {
            true
        }
        (
            OracleStepOutcome::Choices { choices: oc },
            BrinkLineOutcome::Choices {
                presented: bp,
                selected: bs,
            },
        ) => {
            oc.selected == *bs
                && oc.presented.len() == bp.len()
                && oc
                    .presented
                    .iter()
                    .zip(bp.iter())
                    .all(|(o, b)| o.text == b.text && o.index == b.index)
        }
        _ => false,
    }
}

fn format_brink_outcome(outcome: &BrinkLineOutcome) -> String {
    match outcome {
        BrinkLineOutcome::Continue => "Continue".to_string(),
        BrinkLineOutcome::Done => "Done".to_string(),
        BrinkLineOutcome::Ended => "Ended".to_string(),
        BrinkLineOutcome::Choices {
            presented,
            selected,
        } => format!("Choices(selected={selected}, count={})", presented.len()),
    }
}

fn oracle_outcome_eq(oracle: &OracleOutcome, brink: &crate::episode::Outcome) -> bool {
    use crate::episode::Outcome;
    match (oracle, brink) {
        (OracleOutcome::Terminal(s), Outcome::Done | Outcome::Ended)
            if s == "Done" || s == "Ended" =>
        {
            matches!(brink, Outcome::Done | Outcome::Ended)
        }
        (OracleOutcome::InputsExhausted { .. }, Outcome::InputsExhausted { .. })
        | (OracleOutcome::Error { .. }, Outcome::Error(_)) => true,
        _ => false,
    }
}
