//! Oracle episode types and comparison logic.
//!
//! Oracle episodes are generated by the C# ink runtime (tools/ink-oracle)
//! and use string names for variables and container paths. This module
//! handles loading them and comparing against brink's exploration output.

use std::collections::HashMap;
use std::fmt;
use std::path::{Path, PathBuf};

use serde::Deserialize;
use serde_json::Value as JsonValue;

use crate::episode::{Episode, Outcome, StepOutcome};

// ---------------------------------------------------------------------------
// Oracle episode types (deserialized from .oracle.json)
// ---------------------------------------------------------------------------

#[derive(Debug, Deserialize)]
pub struct OracleEpisode {
    pub steps: Vec<OracleStep>,
    pub outcome: OracleOutcome,
    pub choice_path: Vec<usize>,
    pub initial_state: OracleInitialState,
}

#[derive(Debug, Deserialize)]
pub struct OracleStep {
    pub text: String,
    pub tags: Vec<Vec<String>>,
    pub outcome: OracleStepOutcome,
    pub variable_changes: HashMap<String, JsonValue>,
    pub visit_changes: HashMap<String, i64>,
    pub turn_index: i64,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum OracleStepOutcome {
    Terminal(String),
    Choices {
        #[serde(rename = "Choices")]
        choices: OracleChoicesData,
    },
}

#[derive(Debug, Deserialize)]
pub struct OracleChoicesData {
    pub presented: Vec<OracleChoiceRecord>,
    pub selected: usize,
}

#[derive(Debug, Deserialize)]
pub struct OracleChoiceRecord {
    pub text: String,
    pub index: usize,
    pub tags: Vec<String>,
}

#[derive(Debug, Deserialize)]
#[serde(untagged)]
pub enum OracleOutcome {
    Terminal(String),
    InputsExhausted {
        #[serde(rename = "InputsExhausted")]
        data: OracleInputsExhausted,
    },
    Error {
        #[serde(rename = "Error")]
        error: String,
    },
}

#[derive(Debug, Deserialize)]
pub struct OracleInputsExhausted {
    pub remaining_choices: Vec<OracleChoiceRecord>,
}

#[derive(Debug, Deserialize)]
pub struct OracleInitialState {
    pub variables: HashMap<String, JsonValue>,
    pub turn_index: i64,
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

/// Load oracle episode files from a test case's `oracle/` directory.
pub fn load_oracle_episodes(case_dir: &Path) -> Result<Vec<OracleEpisode>, String> {
    let oracle_dir = case_dir.join("oracle");
    if !oracle_dir.is_dir() {
        return Err(format!("no oracle/ directory in {}", case_dir.display()));
    }

    let mut paths: Vec<PathBuf> = std::fs::read_dir(&oracle_dir)
        .map_err(|e| format!("read oracle dir: {e}"))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .and_then(|e| e.to_str())
                .is_some_and(|e| e == "json")
                && p.to_string_lossy().contains(".oracle.")
        })
        .collect();
    paths.sort();

    let mut episodes = Vec::with_capacity(paths.len());
    for path in &paths {
        let content =
            std::fs::read_to_string(path).map_err(|e| format!("read {}: {e}", path.display()))?;
        let ep: OracleEpisode =
            serde_json::from_str(&content).map_err(|e| format!("parse {}: {e}", path.display()))?;
        episodes.push(ep);
    }

    Ok(episodes)
}

// ---------------------------------------------------------------------------
// Comparison
// ---------------------------------------------------------------------------

/// Result of comparing an oracle episode against a brink episode.
#[derive(Debug)]
pub struct OracleDiff {
    pub matches: bool,
    pub step_diffs: Vec<OracleStepDiff>,
    pub outcome_matches: bool,
}

#[derive(Debug)]
pub enum OracleStepDiff {
    Match,
    TextMismatch {
        expected: String,
        actual: String,
    },
    TagsMismatch {
        expected: Vec<Vec<String>>,
        actual: Vec<Vec<String>>,
    },
    OutcomeMismatch {
        expected: String,
        actual: String,
    },
    MissingStep {
        expected_text: String,
    },
    ExtraStep {
        actual_text: String,
    },
}

impl fmt::Display for OracleDiff {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.matches {
            return write!(f, "episodes match");
        }
        writeln!(f, "oracle mismatch:")?;
        for (i, step_diff) in self.step_diffs.iter().enumerate() {
            match step_diff {
                OracleStepDiff::Match => {}
                OracleStepDiff::TextMismatch { expected, actual } => {
                    writeln!(f, "  step {i}: text differs")?;
                    writeln!(f, "    oracle:   {expected:?}")?;
                    writeln!(f, "    brink:    {actual:?}")?;
                }
                OracleStepDiff::TagsMismatch { expected, actual } => {
                    writeln!(f, "  step {i}: tags differ")?;
                    writeln!(f, "    oracle:   {expected:?}")?;
                    writeln!(f, "    brink:    {actual:?}")?;
                }
                OracleStepDiff::OutcomeMismatch { expected, actual } => {
                    writeln!(f, "  step {i}: outcome differs")?;
                    writeln!(f, "    oracle:   {expected}")?;
                    writeln!(f, "    brink:    {actual}")?;
                }
                OracleStepDiff::MissingStep { expected_text } => {
                    writeln!(
                        f,
                        "  step {i}: missing in brink (oracle: {expected_text:?})"
                    )?;
                }
                OracleStepDiff::ExtraStep { actual_text } => {
                    writeln!(f, "  step {i}: extra in brink ({actual_text:?})")?;
                }
            }
        }
        if !self.outcome_matches {
            writeln!(f, "  episode outcome differs")?;
        }
        Ok(())
    }
}

/// Compare an oracle episode against a brink episode.
///
/// Compares text, tags, choices, and outcome. Done/Ended distinction is
/// normalized (both treated as terminal). State writes are not compared
/// (different representation).
pub fn diff_oracle(oracle: &OracleEpisode, brink: &Episode) -> OracleDiff {
    let max_len = oracle.steps.len().max(brink.steps.len());
    let mut step_diffs = Vec::with_capacity(max_len);
    let mut all_match = true;

    for i in 0..max_len {
        match (oracle.steps.get(i), brink.steps.get(i)) {
            (Some(o), Some(b)) => {
                let d = compare_oracle_step(o, b);
                if !matches!(d, OracleStepDiff::Match) {
                    all_match = false;
                }
                step_diffs.push(d);
            }
            (Some(o), None) => {
                all_match = false;
                step_diffs.push(OracleStepDiff::MissingStep {
                    expected_text: o.text.clone(),
                });
            }
            (None, Some(b)) => {
                all_match = false;
                step_diffs.push(OracleStepDiff::ExtraStep {
                    actual_text: b.text.clone(),
                });
            }
            (None, None) => break,
        }
    }

    let outcome_matches = oracle_outcome_eq(&oracle.outcome, &brink.outcome);
    if !outcome_matches {
        all_match = false;
    }

    OracleDiff {
        matches: all_match,
        step_diffs,
        outcome_matches,
    }
}

fn compare_oracle_step(oracle: &OracleStep, brink: &crate::episode::StepRecord) -> OracleStepDiff {
    if oracle.text != brink.text {
        return OracleStepDiff::TextMismatch {
            expected: oracle.text.clone(),
            actual: brink.text.clone(),
        };
    }

    if oracle.tags != brink.tags {
        return OracleStepDiff::TagsMismatch {
            expected: oracle.tags.clone(),
            actual: brink.tags.clone(),
        };
    }

    if !oracle_step_outcome_eq(&oracle.outcome, &brink.outcome) {
        return OracleStepDiff::OutcomeMismatch {
            expected: format!("{:?}", oracle.outcome),
            actual: format!("{:?}", brink.outcome),
        };
    }

    OracleStepDiff::Match
}

/// Compare step outcomes, normalizing Done/Ended (both are "story stopped").
fn oracle_step_outcome_eq(oracle: &OracleStepOutcome, brink: &StepOutcome) -> bool {
    match (oracle, brink) {
        // Done/Ended normalization: treat both as equivalent terminal states.
        (OracleStepOutcome::Terminal(s), StepOutcome::Done | StepOutcome::Ended)
            if s == "Done" || s == "Ended" =>
        {
            matches!(brink, StepOutcome::Done | StepOutcome::Ended)
        }
        (
            OracleStepOutcome::Choices { choices: oc },
            StepOutcome::Choices {
                presented: bp,
                selected: bs,
            },
        ) => {
            oc.selected == *bs
                && oc.presented.len() == bp.len()
                && oc
                    .presented
                    .iter()
                    .zip(bp.iter())
                    .all(|(o, b)| o.text == b.text && o.index == b.index)
        }
        _ => false,
    }
}

/// Compare episode-level outcomes, normalizing Done/Ended.
fn oracle_outcome_eq(oracle: &OracleOutcome, brink: &Outcome) -> bool {
    match (oracle, brink) {
        (OracleOutcome::Terminal(s), Outcome::Done | Outcome::Ended)
            if s == "Done" || s == "Ended" =>
        {
            matches!(brink, Outcome::Done | Outcome::Ended)
        }
        (OracleOutcome::InputsExhausted { .. }, Outcome::InputsExhausted { .. })
        | (OracleOutcome::Error { .. }, Outcome::Error(_)) => true,
        _ => false,
    }
}
