//! The mechanical corpus converter's differential gate (issue #1178): take
//! an existing ink tier-1/tier-2 fixture, mechanically respell it into
//! `.brink` (no hand editing), and assert it plays **episode-identical**
//! to the ink original.
//!
//! The first 9 cases target the exact set
//! `tests/tier1-brink-respell/README.md` already hand-curated as the NF-5
//! (c) differential seed ("a handful of cases spanning weave/choice/
//! tunnel/thread/alternation semantics") — that README says outright these
//! fixtures "will be regenerated by B0.8b's mechanical converter once it
//! exists". This is that converter, proven against the same 9-case target.
//!
//! The cases after that (the "B0.8b gap-closure cases" section) are
//! additional, real oracle-corpus fixtures added while chasing issue
//! #1335's emitter construct-coverage gaps — each pins one specific
//! emitter completeness fix, found via a full-corpus `respell_ink_source`
//! sweep (`crates/internal/brink-respell/tests/full_corpus_sweep.rs`).
//!
//! Both groups together still deliberately do **not** claim the full
//! ~396-case oracle corpus — the README is explicit that the hand-curated
//! seed "is not a mechanical translation of all 390 oracle cases", and
//! mechanizing the full corpus remains later, larger work (the
//! "full-corpus episode-identity differential" `docs/b0-sequencing.md`
//! names as the B0 *ratification* gate, not this one slice's own bar). See
//! `full_corpus_sweep.rs`'s own doc for exactly how far off that gate
//! currently sits and what still blocks it.
//!
//! Entirely additive to the ink pipeline: `explore_from_ink` runs the
//! existing, untouched ink frontend end to end. Nothing here can move the
//! oracle.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use brink_respell::respell_ink_source;
use brink_test_harness::ExploreConfig;
use brink_test_harness::corpus::{explore_from_brink_native_at, explore_from_ink};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("repo root must resolve")
}

fn explore_config() -> ExploreConfig {
    ExploreConfig {
        max_depth: 20,
        max_episodes: 200,
    }
}

/// Respell `ink_rel` (repo-root-relative) into `.brink`, then assert it
/// plays episode-identical to running the ink original directly.
///
/// **Issue #2229 harness fix:** both compare legs must register the *same*
/// file-path qualifier for `hir::stamp_container_ids`'s per-file scoping
/// (#1504, extended to knot interiors by #2229), or the exact same story
/// mints two different `DefinitionId`s for its own anonymous containers —
/// a harness asymmetry, not a story-behavior difference. `explore_from_ink`
/// (below) always compiles through `compile_path`, which registers a real,
/// root-relative key (`brink_driver::relative_key` against the
/// single-file-project root `native_source_root_with_warnings` resolves to
/// — here, `ink_path`'s own directory, since none of this corpus's fixture
/// directories declare a `brink.toml`). The mechanically-respelled `.brink`
/// text has no file of its own to derive that key from — it is compiled
/// in-memory — so it must be handed the *identical* key explicitly via
/// [`explore_from_brink_native_at`] rather than the pathless-default
/// [`brink_test_harness::corpus::explore_from_brink_native`], which the ink
/// leg's real compile never uses.
fn assert_episode_identical(case: &str, ink_rel: &str) {
    let ink_path = repo_root().join(ink_rel);
    let ink_src = std::fs::read_to_string(&ink_path)
        .unwrap_or_else(|e| panic!("{case}: read {}: {e}", ink_path.display()));

    let emitted = respell_ink_source(&ink_src)
        .unwrap_or_else(|e| panic!("{case}: mechanical respell failed: {e}"));

    let config = explore_config();
    let ink_episodes = explore_from_ink(&ink_path, &config)
        .unwrap_or_else(|e| panic!("{case}: exploring the ink original failed: {e}"));

    // Mirror `prepare_driver`'s own root-resolution + relative-key steps
    // (`crates/brink-compiler/src/driver.rs`) so the in-memory `.brink`
    // compile is qualified by the exact same key the real `compile_path`
    // call above registered for `ink_path`.
    let (root, _warnings) = brink_driver::native_source_root_with_warnings(&ink_path);
    let relative_key = brink_driver::relative_key(&root, &ink_path);
    let file_paths: std::collections::HashMap<brink_ir::FileId, String> =
        std::iter::once((brink_ir::FileId(0), relative_key)).collect();

    let brink_episodes = explore_from_brink_native_at(&emitted, &file_paths, &config)
        .unwrap_or_else(|e| {
            panic!("{case}: exploring the mechanically-respelled .brink failed: {e}\n--- emitted ---\n{emitted}")
        });

    assert_eq!(
        ink_episodes, brink_episodes,
        "{case}: episode mismatch (ink original vs. mechanically-respelled .brink)\n--- emitted ---\n{emitted}"
    );
}

#[test]
fn const_vars() {
    assert_episode_identical("const-vars", "tests/tier1/variables/const/story.ink");
}

#[test]
fn basic_tunnel() {
    assert_episode_identical("basic-tunnel", "tests/tier1/diverts/basic-tunnel/story.ink");
}

#[test]
fn simple_glue() {
    assert_episode_identical("simple-glue", "tests/tier1/glue/simple-glue/story.ink");
}

#[test]
fn manual_stitch_v1() {
    assert_episode_identical(
        "manual-stitch-v1",
        "tests/tier1/stitch/manual-stitch-v1/story.ink",
    );
}

#[test]
fn gather_basic() {
    assert_episode_identical("gather-basic", "tests/tier1/gather/gather-basic/story.ink");
}

#[test]
fn complex_flow_v1() {
    assert_episode_identical(
        "complex-flow-v1",
        "tests/tier1/gather/complex-flow-v1/story.ink",
    );
}

#[test]
fn weave_options() {
    assert_episode_identical("weave-options", "tests/tier1/weave/weave-options/story.ink");
}

#[test]
fn sticky_choice() {
    assert_episode_identical(
        "sticky-choice",
        "tests/tier1/choices/sticky-choice/story.ink",
    );
}

#[test]
fn exhibit_fogg_passage() {
    assert_episode_identical(
        "exhibit-fogg-passage",
        "tests/tier2/conditional/condtext-v1/story.ink",
    );
}

// ─── B0.8b gap-closure cases (issue #1335) ──────────────────────────────
//
// Not part of the NF-5 (b) 9-case hand-curated seed above — full-corpus
// oracle cases (`tests/tier1/…`) that the emitter's own completeness bugs
// (not missing native grammar) used to refuse, found via a corpus-wide
// `respell_ink_source` sweep (`full_corpus_sweep.rs`). Two sibling cases
// that motivated the *same* underlying emitter fixes —
// `tests/tier1/choices/varying-choice` and `default-choices` — are
// deliberately **not** here even though the emitter now happily produces
// `.brink` text for both: each fails this differential for a reason
// unrelated to (and not fixed by) this emitter work, traced and left as
// its own finding rather than forced green:
//   - `varying-choice`'s respelled text hits a genuine `E033` "unreachable
//     code after divert" — the trailing `->DONE` this story's last choice
//     absorbs really is dead code (ink's own compiler just never flags
//     it), so brink's analyzer correctly refuses to compile it.
//   - `default-choices`' ` - (start)` sits in *root* content, which
//     `emit_file` wraps in a synthesized `flow main() { … }` (the native
//     story-entry convention) — that gives the `(start)` gather a
//     different qualified address path than the ink original assigns it,
//     so the two runs' `IncrementVisit`/`SetTurnCount` writes carry
//     different `Address` values even though every displayed line and
//     choice matches. A root-content addressing question, not an emitter
//     coverage one.
// Both underlying emitter fixes are still covered: `once_only_choices_…`
// below proves the `else`-body fix end to end, and
// `brink_ir::hir::emit_native::tests` has isolated unit coverage for the
// other two (the ChoiceSet leading shape sidesteps root-content entirely).

#[test]
fn once_only_choices_can_link_back_to_self() {
    // `* -> end` — a choice with no display text at all — lowers with
    // `is_fallback: true` (ink's "no visible option" always-there choice),
    // so its `-> end` body goes through `emit_choice_body` (the `else`
    // path), which never had *any* same-line-divert arm before this fix.
    assert_episode_identical(
        "once-only-choices-can-link-back-to-self",
        "tests/tier1/choices/once-only-choices-can-link-back-to-self/story.ink",
    );
}

// ─── Content-ground logic-line cases (issue #1972) ──────────────────────
//
// `emit_native`'s `Stmt::TempDecl`/`Assignment`/`ExprStmt` arms at
// prose-body position (F1, review of PR #2015): the 42 "assignment" /
// "expression statement" / "temp declaration" cases that moved from
// `respell_ink_source` FAIL to OK were only proven emitter-clean by
// `full_corpus_sweep.rs` (produces `.brink` text, nothing more) — neither
// case had episode-identity coverage in this file until now.

#[test]
fn temporaries_at_global_scope() {
    // `~ temp y = 4` at root content position (issue #1972's `~ let`
    // temp-decl emitter arm), interpolated alongside a `VAR` global —
    // proves the emitted `~ let y = 4` re-parses, re-lowers, and plays
    // identically to the ink original, not just that the emitter accepted
    // the node.
    assert_episode_identical(
        "temporaries-at-global-scope",
        "tests/tier1/variables/I011-temporaries-at-global-scope/story.ink",
    );
}

#[test]
fn rnd_func() {
    // `~ SEED_RANDOM(10)` — a bare call to a builtin at root content
    // position, discarding its return value for side effect only (issue
    // #1972's `ExprStmt` emitter arm) — proves the emitted
    // `~ SEED_RANDOM(10)` re-parses, re-lowers, and plays identically to
    // the ink original, including the downstream `RANDOM(1, 6)` calls
    // whose sequence depends on the seed actually having been applied.
    assert_episode_identical("rnd-func", "tests/tier2/function/rnd-func/story.ink");
}

// ─── `CondKind::IfElse` re-nesting (issue #1975) ────────────────────────
//
// ink's independently-chained, no-shared-subject conditional
// (`{ - cond: … - cond2: … - else: … }`) lowers to `CondKind::IfElse`,
// which `emit_conditional` used to refuse outright — see
// `full_corpus_sweep.rs`'s "IfElse conditional" bucket. `emit_if_else_chain`
// now re-shapes the flat branch list into nested native `{if …} else { {if
// …} else { … } }`, exactly what a native-authored `else if` chain lowers
// to on the way in (`lower_native::cond::lower_conditional`'s doc).

#[test]
fn ifelse_ext_three_way_chain() {
    // Two real conditions plus a trailing `else` (3-way `IfElse`) — the
    // exact shape `emit_conditional`'s old `CondKind::IfElse` arm refused
    // unconditionally.
    assert_episode_identical("ifelse-ext", "tests/tier2/conditional/ifelse-ext/story.ink");
}

// The above proves the re-shape is legal, episode-identical native syntax
// for a chain whose branch bodies carry only `~` assignments (no prose, no
// choices) — the flat→nested reshape's real risk is what happens to
// *content* and `EndOfLine` structure once a branch body becomes the sole
// statement of a synthesized `else { … }` arm, which that case cannot
// exercise. These four content-bearing differentials close that gap: the
// `ifelse-ext-text*` trio is the same 3-way `IfElse` shape with prose
// branch bodies (only the driving `x` value differs, so each of the three
// branches gets taken at least once across the trio), and
// `I113-else-branches` is the choice-shaped variant (`IfElse` and
// `InitialCondition`/`Switch` blocks mixed in the same file, one of them
// with a bare-inline branch body rather than an indented block).

#[test]
fn ifelse_ext_text1() {
    assert_episode_identical(
        "ifelse-ext-text1",
        "tests/tier2/conditional/ifelse-ext-text1/story.ink",
    );
}

#[test]
fn ifelse_ext_text2() {
    assert_episode_identical(
        "ifelse-ext-text2",
        "tests/tier2/conditional/ifelse-ext-text2/story.ink",
    );
}

#[test]
fn ifelse_ext_text3() {
    assert_episode_identical(
        "ifelse-ext-text3",
        "tests/tier2/conditional/ifelse-ext-text3/story.ink",
    );
}

#[test]
fn i113_else_branches() {
    assert_episode_identical(
        "I113-else-branches",
        "tests/tier2/conditions/I113-else-branches/story.ink",
    );
}

// ─── `fn`-body prose-override selector (issue #2044) ────────────────────
//
// `tests/tier2/function/complex-func2/story.ink`'s `=== function derp(a,
// b) ===` knot mixes a `VAR`-turned-declaration, a mid-body `~ x = a - b`
// assignment, and a follow-on `IfElse`-shaped conditional block in the
// same ink source body — the exact "mid-body statement after an
// inline-conditional VAR chain" shape #2044 named. Note the `VAR`s hoist
// to file-level globals on the way through the mechanical respell (the
// emitted `.brink` puts `var x = 0` / `var y = 3` / `var z = 1` before
// `flow main()`), so the emitted `fn derp` body itself carries only the
// assignment and the conditional, not a declaration — it's the *ink*
// source, not the emitted knot body, that mixes all three. At filing
// time this failed to reparse
// (`expected an expression, found TILDE`): `emit_knot` wrote a bare `{`
// for every `fn`, which selects native's code-ground (`;`-terminated)
// statement dialect, but the printer's statement stream only ever spells
// prose-ground syntax.
//
// That root cause was already fixed by PR #2039 (closing #2029, merged
// before this issue's assigned work began) — `emit_knot` now spells the
// `>{ }` prose-ground override for every `fn` body. This test is the
// round-trip differential #2044 asked for: no `ink_corpus_convert.rs`
// case exercised an ink-derived `fn` knot's body before now, so the
// `>{ }` fix had no episode-identity proof against a real oracle-corpus
// `fn`. See `docs/decision-log.md` or issue #2029 for the fix itself —
// this PR adds test coverage only, not a production change.
#[test]
fn complex_func2_fn_body_mid_statement() {
    assert_episode_identical(
        "complex-func2",
        "tests/tier2/function/complex-func2/story.ink",
    );
}
