//! The mechanical corpus converter's differential gate (issue #1178): take
//! an existing ink tier-1/tier-2 fixture, mechanically respell it into
//! `.brink` (no hand editing), and assert it plays **episode-identical**
//! to the ink original.
//!
//! This targets the exact 9 cases `tests/tier1-brink-respell/README.md`
//! already hand-curated as the NF-5 (c) differential seed ("a handful of
//! cases spanning weave/choice/tunnel/thread/alternation semantics") —
//! that README says outright these fixtures "will be regenerated by
//! B0.8b's mechanical converter once it exists". This is that converter,
//! proven against the same 9-case target. It deliberately does **not**
//! claim the full 390-case oracle corpus — the README is explicit that the
//! hand-curated seed "is not a mechanical translation of all 390 oracle
//! cases", and mechanizing the full corpus remains later, larger work (the
//! "full-corpus episode-identity differential" `docs/b0-sequencing.md`
//! names as the B0 *ratification* gate, not this one slice's own bar).
//!
//! Entirely additive to the ink pipeline: `explore_from_ink` runs the
//! existing, untouched ink frontend end to end. Nothing here can move the
//! oracle.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]

use std::path::{Path, PathBuf};

use brink_respell::respell_ink_source;
use brink_test_harness::ExploreConfig;
use brink_test_harness::corpus::{explore_from_brink_native, explore_from_ink};

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../..")
        .canonicalize()
        .expect("repo root must resolve")
}

fn explore_config() -> ExploreConfig {
    ExploreConfig {
        max_depth: 20,
        max_episodes: 200,
    }
}

/// Respell `ink_rel` (repo-root-relative) into `.brink`, then assert it
/// plays episode-identical to running the ink original directly.
fn assert_episode_identical(case: &str, ink_rel: &str) {
    let ink_path = repo_root().join(ink_rel);
    let ink_src = std::fs::read_to_string(&ink_path)
        .unwrap_or_else(|e| panic!("{case}: read {}: {e}", ink_path.display()));

    let emitted = respell_ink_source(&ink_src)
        .unwrap_or_else(|e| panic!("{case}: mechanical respell failed: {e}"));

    let config = explore_config();
    let ink_episodes = explore_from_ink(&ink_path, &config)
        .unwrap_or_else(|e| panic!("{case}: exploring the ink original failed: {e}"));
    let brink_episodes = explore_from_brink_native(&emitted, &config).unwrap_or_else(|e| {
        panic!("{case}: exploring the mechanically-respelled .brink failed: {e}\n--- emitted ---\n{emitted}")
    });

    assert_eq!(
        ink_episodes, brink_episodes,
        "{case}: episode mismatch (ink original vs. mechanically-respelled .brink)\n--- emitted ---\n{emitted}"
    );
}

#[test]
fn const_vars() {
    assert_episode_identical("const-vars", "tests/tier1/variables/const/story.ink");
}

#[test]
fn basic_tunnel() {
    assert_episode_identical("basic-tunnel", "tests/tier1/diverts/basic-tunnel/story.ink");
}

#[test]
fn simple_glue() {
    assert_episode_identical("simple-glue", "tests/tier1/glue/simple-glue/story.ink");
}

#[test]
fn manual_stitch_v1() {
    assert_episode_identical(
        "manual-stitch-v1",
        "tests/tier1/stitch/manual-stitch-v1/story.ink",
    );
}

#[test]
fn gather_basic() {
    assert_episode_identical("gather-basic", "tests/tier1/gather/gather-basic/story.ink");
}

#[test]
fn complex_flow_v1() {
    assert_episode_identical(
        "complex-flow-v1",
        "tests/tier1/gather/complex-flow-v1/story.ink",
    );
}

#[test]
fn weave_options() {
    assert_episode_identical("weave-options", "tests/tier1/weave/weave-options/story.ink");
}

#[test]
fn sticky_choice() {
    assert_episode_identical(
        "sticky-choice",
        "tests/tier1/choices/sticky-choice/story.ink",
    );
}

#[test]
fn exhibit_fogg_passage() {
    assert_episode_identical(
        "exhibit-fogg-passage",
        "tests/tier2/conditional/condtext-v1/story.ink",
    );
}
