[package]
name = "brink-loop"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
brink-format = { path = "../../../crates/internal/brink-format" }
brink-runtime = { path = "../../../crates/brink-runtime" }
brink-compiler = { path = "../../../crates/brink-compiler" }

[profile.release]
debug = true
