id = "ink"
name = "Ink"
version = "0.0.1"
schema_version = 1
authors = ["brink contributors"]
description = "Ink narrative scripting language support"

[grammars.ink]
repository = "file:///Users/syynth/code/rs/brink/tree-sitter-ink"
rev = "6a9e3225f8536c530a99955b3b134b97327bd5e2"

[language_servers.brink-lsp]
languages = ["Ink"]
