//! Oracle comparison test: compile `.ink` with the brink compiler,
//! explore, and diff against oracle episodes (generated by the C# ink runtime).
//!
//! This reveals behavioral divergences between brink and the reference
//! C# ink runtime. Unlike the converter-based golden episodes, oracle
//! episodes come directly from running the actual ink runtime.
//!
//! Set `BRINK_CASE` to a substring to filter to a single test case, e.g.:
//!   `BRINK_CASE=I002 cargo test -p brink-test-harness --test oracle_comparison -- --nocapture`

use std::collections::HashMap;
use std::path::PathBuf;

use brink_test_harness::corpus::{collect_oracle_cases, compile_and_explore_from_ink};
use brink_test_harness::oracle;
use brink_test_harness::{Episode, ExploreConfig};

fn tests_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("..")
        .join("tests")
}

/// Returns true if the case's metadata.toml has `mode = "compile_error"`.
fn is_compile_error_case(case_dir: &std::path::Path) -> bool {
    let meta_path = case_dir.join("metadata.toml");
    std::fs::read_to_string(meta_path).ok().is_some_and(|s| {
        s.lines()
            .any(|line| line.trim() == r#"mode = "compile_error""#)
    })
}

fn has_empty_source(case_dir: &std::path::Path) -> bool {
    let ink_path = case_dir.join("story.ink");
    std::fs::read_to_string(ink_path)
        .ok()
        .is_some_and(|s| s.trim().is_empty())
}

fn index_by_choice_path(episodes: &[Episode]) -> HashMap<&[usize], &Episode> {
    episodes
        .iter()
        .map(|ep| (ep.choice_path.as_slice(), ep))
        .collect()
}

/// Ratchet: minimum number of oracle episodes that must pass.
/// Bump this as compiler coverage improves.
const RATCHET_EPISODE_COUNT: usize = 3500;

#[test]
#[expect(clippy::too_many_lines)]
fn oracle_comparison() {
    let root = tests_dir();
    let cases = collect_oracle_cases(&root);
    let case_filter = std::env::var("BRINK_CASE").ok();

    let config = ExploreConfig {
        max_depth: 20,
        max_episodes: 1000,
    };

    let mut cases_pass = 0;
    let mut cases_mismatch = 0;
    let mut compile_error = 0;
    let mut link_error = 0;
    let mut skip = 0;

    let mut episodes_pass = 0;
    let mut episodes_mismatch = 0;
    let mut episodes_total = 0;
    let mut episodes_missing = 0;

    let mut first_mismatch: Option<String> = None;
    let mut failing_cases: Vec<String> = Vec::new();

    for case_dir in &cases {
        let rel = case_dir
            .strip_prefix(&root)
            .unwrap_or(case_dir)
            .display()
            .to_string();

        if let Some(ref filter) = case_filter
            && !rel.contains(filter.as_str())
        {
            continue;
        }

        let ink_path = case_dir.join("story.ink");
        if !ink_path.exists() || has_empty_source(case_dir) || is_compile_error_case(case_dir) {
            skip += 1;
            continue;
        }

        // Load oracle episodes.
        let oracle_eps = match oracle::load_oracle_episodes(case_dir) {
            Ok(eps) if eps.is_empty() => {
                skip += 1;
                continue;
            }
            Ok(eps) => eps,
            Err(_) => {
                skip += 1;
                continue;
            }
        };

        // Compile with brink.
        let actual = match compile_and_explore_from_ink(&ink_path, &config) {
            Ok((_data, episodes)) => episodes,
            Err(e) if e.starts_with("compile:") => {
                compile_error += 1;
                failing_cases.push(format!("{rel} ({e})"));
                if first_mismatch.is_none() {
                    first_mismatch = Some(format!("{rel}: {e}"));
                }
                continue;
            }
            Err(e) if e.starts_with("link:") => {
                link_error += 1;
                failing_cases.push(format!("{rel} (link error)"));
                if first_mismatch.is_none() {
                    first_mismatch = Some(format!("{rel}: {e}"));
                }
                continue;
            }
            Err(e) => {
                compile_error += 1;
                failing_cases.push(format!("{rel} ({e})"));
                if first_mismatch.is_none() {
                    first_mismatch = Some(format!("{rel}: {e}"));
                }
                continue;
            }
        };

        let actual_index = index_by_choice_path(&actual);
        episodes_total += oracle_eps.len();

        if case_filter.is_some() {
            for (i, ep) in actual.iter().enumerate() {
                println!(
                    "  actual[{i}]: path={:?} outcome={:?}",
                    ep.choice_path, ep.outcome
                );
            }
            println!("  oracle episodes: {}", oracle_eps.len());
            println!("  brink episodes:  {}", actual.len());
        }

        let mut case_ok = true;

        for (i, oracle_ep) in oracle_eps.iter().enumerate() {
            let Some(brink_ep) = actual_index.get(oracle_ep.choice_path.as_slice()) else {
                case_ok = false;
                episodes_missing += 1;
                if first_mismatch.is_none() {
                    first_mismatch = Some(format!(
                        "{rel}: oracle episode {i} choice_path {:?} not found in brink \
                         (oracle has {}, brink has {} episodes)",
                        oracle_ep.choice_path,
                        oracle_eps.len(),
                        actual.len()
                    ));
                }
                continue;
            };

            let d = oracle::diff_oracle(oracle_ep, brink_ep);
            if d.matches {
                episodes_pass += 1;
            } else {
                episodes_mismatch += 1;
                case_ok = false;
                if first_mismatch.is_none() {
                    first_mismatch = Some(format!("{rel}: oracle episode {i}:\n{d}"));
                }
            }
        }

        if case_ok {
            cases_pass += 1;
        } else {
            cases_mismatch += 1;
            failing_cases.push(rel);
        }
    }

    let total_cases = cases.len();
    println!();
    println!(
        "ORACLE CASES: {cases_pass} pass / {cases_mismatch} mismatch / \
         {compile_error} compile_error / {link_error} link_error / \
         {skip} skip (of {total_cases})"
    );
    println!(
        "ORACLE EPISODES: {episodes_pass} pass / {episodes_mismatch} mismatch / \
         {episodes_missing} missing (of {episodes_total} oracle)"
    );

    if !failing_cases.is_empty() {
        println!("\nFailing cases ({}):", failing_cases.len());
        for name in &failing_cases {
            println!("  {name}");
        }
    }

    if let Some(ref msg) = first_mismatch {
        println!();
        println!("First mismatch:\n{msg}");
    }

    if case_filter.is_some() {
        assert!(
            episodes_mismatch == 0 && episodes_missing == 0,
            "{episodes_mismatch} episode(s) mismatched, {episodes_missing} missing"
        );
    } else {
        assert!(
            episodes_pass >= RATCHET_EPISODE_COUNT,
            "ratchet regression: {episodes_pass} episodes < {RATCHET_EPISODE_COUNT}"
        );
    }
}
