[package]
name = "brink-fmt"
description = "Source code formatter for inkle's ink narrative scripting language"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
brink-ir = { workspace = true }
brink-project-config = { workspace = true }
brink-syntax = { workspace = true }
rowan.workspace = true

[dev-dependencies]
insta.workspace = true

[lints]
workspace = true
