[package]
name = "brink-codegen-inkb"
description = "Bytecode codegen backend: LIR → StoryData (inkb format)"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
brink-ir = { workspace = true }
brink-format = { workspace = true }

[lints]
workspace = true
