[package]
name = "brink-ir"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Intermediate representations for inkle's ink narrative scripting language"

[dependencies]
brink-syntax = { workspace = true }
brink-format = { workspace = true }
rowan.workspace = true
bitflags.workspace = true
tracing.workspace = true
serde = { workspace = true }
thiserror.workspace = true
regex.workspace = true

[dev-dependencies]
brink-analyzer = { path = "../brink-analyzer" }
brink-codegen-inkb = { path = "../brink-codegen-inkb" }
insta.workspace = true
serde_json.workspace = true

[lints]
workspace = true
