//! Inline-markup vocabulary validation against the host capability manifest
//! (`docs/prose-dialect-spec.md` §4.2, issue #1733).
//!
//! §4.2's ruling has two halves. The first — **freeform by default** — landed
//! with the markup grammar itself (PR #1732): an unrecognized `<tag>` is
//! never a parse error, and nothing here changes that. This module is the
//! second half: *when the host manifest declares a markup vocabulary*, span
//! names and attributes are checked against it.
//!
//! # Freeform stays the default
//!
//! [`check`] returns immediately — before touching the HIR at all — unless
//! the registered manifest declares at least one span kind. That is not an
//! optimization: it is the ruling. A project with no manifest, *and* a
//! project whose manifest declares only `externals`/`types`, must behave
//! exactly as they did before this module existed. `markup` is opt-in
//! tightening, never a tax on hosts that never asked for it.
//!
//! # Where the vocabulary lives
//!
//! In the **host capability manifest**, alongside `externals` — §3.4's
//! authorship test ("co-locate declarations only if hand-authored or
//! generated by the same source"): markup vocabulary is host-authored and can
//! be generated from engine code, the way bindings generate externals.
//! Element conventions are project-authored and live in the
//! `brink.toml`-referenced conventions module instead; the two are not the
//! same surface.
//!
//! # Severity
//!
//! `E164`/`E165` default to `Warning`, which is exactly what makes them
//! configurable: `[lints] E164 = "deny"` promotes a declared vocabulary to
//! binding, `[lints] E164 = "allow"`/`@[allow(E164)]`/`// brink-disable E164`
//! turn a check off for a project, a declaration, or a line. Hard-error
//! codes are neither overridable nor suppressible (`brink_ir::suppressions`),
//! so `Warning` is the only base that satisfies §4.2's "configurable
//! severity".

use std::collections::{BTreeMap, BTreeSet};

use brink_ir::hir::{Content, ContentContext, ContentPart, HirFile, HirVisitor, SpanPart};
use brink_ir::{Diagnostic, DiagnosticCode, FileId, HostManifest};

/// Check every inline markup span in `files` against the manifest's declared
/// markup vocabulary.
///
/// Returns an empty vector when no vocabulary is declared (the freeform
/// default) — see the module doc.
#[must_use]
pub fn check(files: &[(FileId, &HirFile)], manifest: Option<&HostManifest>) -> Vec<Diagnostic> {
    let Some(manifest) = manifest else {
        return Vec::new();
    };
    if manifest.markup.is_empty() {
        return Vec::new();
    }

    // `BTreeMap`/`BTreeSet` (not `HashMap`): a duplicate declaration of the
    // same kind merges deterministically, and diagnostic *messages* quote
    // nothing iteration-ordered, so this is order-insensitive by
    // construction rather than by luck.
    let mut vocab: BTreeMap<&str, BTreeSet<&str>> = BTreeMap::new();
    for kind in &manifest.markup {
        let entry = vocab.entry(kind.name.as_str()).or_default();
        entry.extend(kind.attrs.iter().map(String::as_str));
    }

    let mut out = Vec::new();
    for &(file, hir) in files {
        let mut walker = SpanWalker {
            file,
            vocab: &vocab,
            out: &mut out,
        };
        brink_ir::hir::visit::visit(hir, &mut walker);
    }
    out
}

/// Collects markup diagnostics for one file.
///
/// Descends into spans by hand rather than relying on the shared walker:
/// [`HirVisitor`]'s content hook hands over the whole [`Content`], and
/// `walk_content_part` recurses *through* a span into its children without
/// exposing the [`SpanPart`] itself (a span is presentational, so structural
/// walkers see past it). This is the one pass that needs the span node.
struct SpanWalker<'a> {
    file: FileId,
    vocab: &'a BTreeMap<&'a str, BTreeSet<&'a str>>,
    out: &'a mut Vec<Diagnostic>,
}

impl SpanWalker<'_> {
    /// Report against the enclosing content line's range.
    ///
    /// A [`SpanPart`] carries no [`Provenance`](brink_ir::Provenance) of its
    /// own (v1: it is a plain inline content fragment, like `Text`/`Glue`),
    /// so the line is the narrowest range available. Every diagnostic here
    /// names the offending tag/attribute in its message, so a line carrying
    /// several spans stays unambiguous.
    fn report(&mut self, content: &Content, code: DiagnosticCode, message: String) {
        let Some(ptr) = content.ptr.as_ref() else {
            return;
        };
        self.out.push(Diagnostic {
            file: self.file,
            range: ptr.text_range(),
            message,
            code,
        });
    }

    fn check_span(&mut self, content: &Content, span: &SpanPart) {
        match self.vocab.get(span.name.as_str()) {
            None => self.report(
                content,
                DiagnosticCode::E164,
                format!(
                    "unknown markup tag `<{}>`: the host manifest's markup vocabulary does not declare it",
                    span.name
                ),
            ),
            Some(allowed) => {
                for (attr, _value) in &span.attrs {
                    if !allowed.contains(attr.as_str()) {
                        self.report(
                            content,
                            DiagnosticCode::E165,
                            format!(
                                "unknown attribute `{attr}` on markup tag `<{}>`: the host manifest does not declare it for this span kind",
                                span.name
                            ),
                        );
                    }
                }
            }
        }
        for child in &span.children {
            self.check_part(content, child);
        }
    }

    fn check_part(&mut self, content: &Content, part: &ContentPart) {
        match part {
            ContentPart::Span(span) => self.check_span(content, span),
            // Logic nests freely inside markup and vice versa (§4.3), so a
            // span can hide inside an inline conditional's or sequence's
            // branch content. Those branches are `Content` nodes of their
            // own and the shared walker delivers them through
            // `enter_content` in turn — nothing to recurse into here.
            ContentPart::Text(_)
            | ContentPart::Glue
            | ContentPart::Spring
            | ContentPart::Interpolation(_)
            | ContentPart::InlineConditional(_)
            | ContentPart::InlineSequence(_) => {}
        }
    }
}

impl HirVisitor for SpanWalker<'_> {
    fn enter_content(&mut self, content: &Content, _ctx: ContentContext) {
        // `content.parts` only — deliberately *not* `content.tags`, even
        // though a `Tag` structurally owns a `Vec<ContentPart>` too. The
        // native frontend's `lower_tag` concatenates a tag's raw token text
        // into exactly one `ContentPart::Text`, so no `Span` can ever appear
        // under a tag; descending there would be unreachable code. (A `#`
        // tag written with markup in it keeps the angle brackets as literal
        // tag text — tags are metadata, not prose.) If tag lowering ever
        // gains real content parts, this is the line that has to change.
        for part in &content.parts {
            self.check_part(content, part);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use brink_ir::{ManifestExternal, ManifestSpanKind, SemanticTypeDef};

    fn lower(src: &str) -> HirFile {
        let parse = brink_syntax_native::parse(src);
        assert!(
            parse.errors().is_empty(),
            "parse errors: {:?}",
            parse.errors()
        );
        let (hir, _manifest, diags) = brink_ir::hir::lower_native::lower(FileId(0), &parse.tree());
        assert!(diags.is_empty(), "lowering diagnostics: {diags:?}");
        hir
    }

    fn run(src: &str, manifest: Option<&HostManifest>) -> Vec<Diagnostic> {
        let hir = lower(src);
        check(&[(FileId(0), &hir)], manifest)
    }

    fn codes(diags: &[Diagnostic]) -> Vec<&'static str> {
        diags.iter().map(|d| d.code.as_str()).collect()
    }

    /// A vocabulary declaring `<wave amount="…">` and a bare `<b>`.
    fn wave_manifest() -> HostManifest {
        HostManifest {
            markup: vec![
                ManifestSpanKind {
                    name: "wave".to_string(),
                    attrs: vec!["amount".to_string()],
                },
                ManifestSpanKind {
                    name: "b".to_string(),
                    attrs: Vec::new(),
                },
            ],
            ..HostManifest::default()
        }
    }

    // ── Freeform by default (§4.2, the half that must not regress) ──────

    #[test]
    fn no_manifest_at_all_never_diagnoses_a_span() {
        let diags = run(
            "flow a() {\n  He hands you <item id=\"lantern\">the lantern</item>.\n}\n",
            None,
        );
        assert!(
            diags.is_empty(),
            "freeform default must stay silent: {diags:?}"
        );
    }

    #[test]
    fn a_manifest_with_externals_but_no_markup_key_never_diagnoses_a_span() {
        // The load-bearing case: registering a manifest for the *externals*
        // vocabulary must not silently opt a project into markup checking.
        // `markup` is what tightens; nothing else does.
        let manifest = HostManifest {
            externals: vec![ManifestExternal {
                name: "play_sfx".to_string(),
                params: Vec::new(),
                returns: brink_ir::TypeRef::default(),
                kind: brink_ir::ExternalKind::default(),
                doc: None,
                widgets: Vec::new(),
                path: Vec::new(),
            }],
            types: vec![SemanticTypeDef {
                name: "actor_id".to_string(),
                base: brink_ir::BaseType::Int,
                constraint: None,
                values: None,
                widget: None,
            }],
            markup: Vec::new(),
        };
        let diags = run(
            "flow a() {\n  <totally undeclared=\"yes\">hi</totally>\n}\n",
            Some(&manifest),
        );
        assert!(
            diags.is_empty(),
            "an externals-only manifest must not enable markup checking: {diags:?}"
        );
    }

    #[test]
    fn a_declared_vocabulary_still_accepts_every_declared_tag() {
        let diags = run(
            "flow a() {\n  <wave amount=\"3\">shimmer</wave> and <b>bold</b>\n}\n",
            Some(&wave_manifest()),
        );
        assert!(diags.is_empty(), "declared tags must pass: {diags:?}");
    }

    // ── Manifest-validated (the half this module adds) ──────────────────

    #[test]
    fn an_undeclared_tag_reports_e164_once() {
        let diags = run(
            "flow a() {\n  <shake power=\"9\">whoa</shake>\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164"], "{diags:?}");
        assert!(
            diags[0].message.contains("<shake>"),
            "message must name the tag: {}",
            diags[0].message
        );
    }

    #[test]
    fn an_undeclared_attribute_on_a_declared_tag_reports_e165() {
        let diags = run(
            "flow a() {\n  <wave speed=\"2\">shimmer</wave>\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E165"], "{diags:?}");
        assert!(
            diags[0].message.contains("speed") && diags[0].message.contains("<wave>"),
            "message must name attribute and tag: {}",
            diags[0].message
        );
    }

    #[test]
    fn an_undeclared_tag_does_not_cascade_one_e165_per_attribute() {
        let diags = run(
            "flow a() {\n  <shake power=\"9\" decay=\"1\">whoa</shake>\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164"], "{diags:?}");
    }

    #[test]
    fn a_self_closing_undeclared_tag_reports_e164() {
        let diags = run(
            "flow a() {\n  Bell tolls. <pause/> Door slams.\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164"], "{diags:?}");
    }

    #[test]
    fn a_nested_span_is_checked_not_just_the_outermost() {
        let diags = run(
            "flow a() {\n  <b><glitch>hi</glitch></b>\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164"], "{diags:?}");
        assert!(
            diags[0].message.contains("<glitch>"),
            "{}",
            diags[0].message
        );
    }

    #[test]
    fn a_span_inside_a_conditional_branch_is_checked() {
        // §4.3 lets logic and markup nest freely; the branch body is its own
        // `Content` node, so this proves the walker reaches it.
        let diags = run(
            "flow a(hp) {\n  {if hp > 0: <glitch>yawn</glitch> else: Ready.}\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164"], "{diags:?}");
    }

    #[test]
    fn a_span_in_a_choice_display_line_is_checked() {
        // A choice's inline slots are `Content` nodes the shared walker
        // delivers under a different `ContentContext` — markup there must not
        // be a blind spot just because it isn't a body line.
        let diags = run(
            "flow a() {\n  * <glitch>Take it</glitch>\n    Done.\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164"], "{diags:?}");
    }

    #[test]
    fn markup_written_inside_a_tag_is_tag_text_not_a_span() {
        // Pins `enter_content`'s reason for skipping `content.tags`: native
        // `lower_tag` flattens a tag's raw tokens into one `Text` part, so
        // there is no `Span` under a tag to check. Guards the skip — if tag
        // lowering ever produces real content parts, this goes red and the
        // walker has to grow a tag descent.
        let hir = lower("flow a() {\n  Hello. # <glitch>loud</glitch>\n}\n");
        let tags: Vec<_> = hir
            .knots
            .iter()
            .flat_map(|k| &k.body.stmts)
            .filter_map(|s| match s {
                brink_ir::hir::Stmt::Content(c) => Some(&c.tags),
                _ => None,
            })
            .flatten()
            .collect();
        assert!(!tags.is_empty(), "fixture must produce a tag: {hir:?}");
        for tag in tags {
            assert!(
                tag.parts.iter().all(|p| matches!(p, ContentPart::Text(_))),
                "a tag must lower to Text only, never a Span: {:?}",
                tag.parts
            );
        }
    }

    #[test]
    fn every_undeclared_tag_on_one_line_is_reported() {
        let diags = run(
            "flow a() {\n  <glitch>a</glitch> and <shake>b</shake>\n}\n",
            Some(&wave_manifest()),
        );
        assert_eq!(codes(&diags), ["E164", "E164"], "{diags:?}");
    }

    // ── Severity is configurable, which needs a `Warning` base ──────────

    #[test]
    fn both_codes_default_to_warning_so_they_stay_overridable_and_suppressible() {
        // `[lints]` overrides and `@[allow(…)]` both refuse `Error`-base
        // codes outright (`brink_ir::suppressions`), so this *is* the
        // "configurable severity" requirement, not a cosmetic choice.
        assert_eq!(DiagnosticCode::E164.severity(), brink_ir::Severity::Warning);
        assert_eq!(DiagnosticCode::E165.severity(), brink_ir::Severity::Warning);
    }

    // ── Determinism ─────────────────────────────────────────────────────

    #[test]
    fn duplicate_kind_declarations_merge_their_attribute_sets() {
        let manifest = HostManifest {
            markup: vec![
                ManifestSpanKind {
                    name: "wave".to_string(),
                    attrs: vec!["amount".to_string()],
                },
                ManifestSpanKind {
                    name: "wave".to_string(),
                    attrs: vec!["speed".to_string()],
                },
            ],
            ..HostManifest::default()
        };
        let diags = run(
            "flow a() {\n  <wave amount=\"3\">x</wave> <wave speed=\"2\">y</wave>\n}\n",
            Some(&manifest),
        );
        assert!(diags.is_empty(), "both attrs must be accepted: {diags:?}");
    }
}
