[package]
name = "brink-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Pipeline orchestration for the brink ink compiler"

[dependencies]
brink-db = { workspace = true }
brink-analyzer = { workspace = true }
brink-ir = { workspace = true }
brink-project-config = { workspace = true }
brink-source-tree = { workspace = true }
tracing.workspace = true
thiserror.workspace = true

[lints]
workspace = true
