//! CLI parsing, the checked-in baseline matrix, and CSV/markdown report
//! writers for the scenario harness (issue #900, BH-B-1). See
//! `benches/scenario_bench.rs`'s module docs for the full write-up.
#![expect(
    clippy::print_stdout,
    reason = "benchmark harness: the printed matrix is the product (same stance as compile_bench/runtime-bench)"
)]

use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::PathBuf;

use super::model::{ScenarioConfig, ScenarioResult, TurnWeight, run_scenario};

// ── CSV + markdown matrix output ────────────────────────────────────────

const CSV_HEADER: &str = "name,flow_count,active_fraction,world_size,turn_weight,frames,seed,\
frame_p50_ms,frame_p99_ms,collect_p50_us,step_p50_us,apply_p50_us,turns_per_sec,\
turns_completed,flow_anomalies,rss_before_kb,rss_after_kb,rss_delta_kb,cow_copies,arc_clones";

fn opt_u64(v: Option<u64>) -> String {
    v.map_or_else(|| "n/a".to_string(), |x| x.to_string())
}
fn opt_i64(v: Option<i64>) -> String {
    v.map_or_else(|| "n/a".to_string(), |x| x.to_string())
}

fn csv_row(r: &ScenarioResult) -> String {
    format!(
        "{},{},{},{},{},{},{},{:.4},{:.4},{:.4},{:.4},{:.4},{:.2},{},{},{},{},{},{},{}",
        r.name,
        r.flow_count,
        r.active_fraction,
        r.world_size,
        r.turn_weight.label(),
        r.frames,
        r.seed,
        r.frame_p50_ms,
        r.frame_p99_ms,
        r.collect_p50_us,
        r.step_p50_us,
        r.apply_p50_us,
        r.turns_per_sec,
        r.turns_completed,
        r.flow_anomalies,
        opt_u64(r.rss_before_kb),
        opt_u64(r.rss_after_kb),
        opt_i64(r.rss_delta_kb),
        opt_u64(r.cow_copies),
        opt_u64(r.arc_clones),
    )
}

fn write_csv(results: &[ScenarioResult], path: &std::path::Path) -> io::Result<()> {
    let mut out = String::from(CSV_HEADER);
    out.push('\n');
    for r in results {
        out.push_str(&csv_row(r));
        out.push('\n');
    }
    fs::write(path, out)
}

fn write_markdown(results: &[ScenarioResult], path: &std::path::Path) -> io::Result<()> {
    let mut out = String::new();
    out.push_str("# Scenario harness — SERIAL-driver baselines (issue #900)\n\n");
    out.push_str(
        "Generated by `cargo bench -p bevy-brink --bench scenario_bench`. See \
         `docs/bevy-bench.md` for the honesty caveats (what each column can and \
         can't see) and regeneration instructions. Absolute numbers are \
         machine-specific and will drift — this is a baseline for `BH-3`'s \
         later parallel-vs-serial comparison, not a strict pass/fail gate.\n\n",
    );
    out.push_str(
        "| scenario | flows | active | world | turn | frames | frame p50 (ms) | frame p99 (ms) | collect p50 (µs) | step p50 (µs) | apply p50 (µs) | turns/sec | turns | anomalies | rss Δ (KB) | cow_copies | arc_clones |\n",
    );
    out.push_str(
        "|---|---:|---:|---:|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|\n",
    );
    for r in results {
        let _ = writeln!(
            out,
            "| {} | {} | {:.0}% | {} | {} | {} | {:.3} | {:.3} | {:.2} | {:.2} | {:.2} | {:.1} | {} | {} | {} | {} | {} |",
            r.name,
            r.flow_count,
            r.active_fraction * 100.0,
            r.world_size,
            r.turn_weight.label(),
            r.frames,
            r.frame_p50_ms,
            r.frame_p99_ms,
            r.collect_p50_us,
            r.step_p50_us,
            r.apply_p50_us,
            r.turns_per_sec,
            r.turns_completed,
            r.flow_anomalies,
            opt_i64(r.rss_delta_kb),
            opt_u64(r.cow_copies),
            opt_u64(r.arc_clones),
        );
    }
    fs::write(path, out)
}

// ── Baseline matrix + CLI ───────────────────────────────────────────────

const DEFAULT_FRAMES: usize = 30;
/// Fixed active:parked ratio and turn weight for the checked-in baselines
/// — only `flow_count` varies, per the issue's "baselines at 1/100/1k/10k
/// flows" ask. `world_size` is held at 0 so these baselines isolate
/// flow-count scaling cleanly; non-zero `world_size` is an exploration
/// axis for later `BH-3` work, not this seed's baseline matrix.
const BASELINE_ACTIVE_FRACTION: f64 = 0.7;
const BASELINE_WORLD_SIZE: usize = 0;
const BASELINE_TURN_WEIGHT: TurnWeight = TurnWeight::Medium;
const BASELINE_SEED: u64 = 0x5CEE_0900_BEEF_CAFE;

fn parse_frames() -> Result<usize, Box<dyn std::error::Error>> {
    let args: Vec<String> = std::env::args().collect();
    for w in args.windows(2) {
        if w[0] == "--frames" {
            return Ok(w[1].parse()?);
        }
    }
    Ok(DEFAULT_FRAMES)
}

/// The four checked-in flow-count baselines (`turn_weight` fixed at
/// [`BASELINE_TURN_WEIGHT`]), plus two small supplementary rows that
/// exercise the `turn_weight` axis itself (`Light`/`Heavy`) at a fixed,
/// modest flow count — proving the axis is actually wired end to end
/// (generator → compiled program → driven turns), not merely declared in
/// `ScenarioConfig` and never reached.
fn baseline_configs(frames: usize) -> Vec<ScenarioConfig> {
    let flow_count_rows = [
        ("serial-1", 1),
        ("serial-100", 100),
        ("serial-1k", 1_000),
        ("serial-10k", 10_000),
    ]
    .into_iter()
    .map(|(name, flow_count)| ScenarioConfig {
        name: name.to_string(),
        flow_count,
        active_fraction: BASELINE_ACTIVE_FRACTION,
        world_size: BASELINE_WORLD_SIZE,
        turn_weight: BASELINE_TURN_WEIGHT,
        frames,
        seed: BASELINE_SEED,
        // The checked-in baselines stay scalar-only (docs/bevy-bench.md's
        // honesty note on cow_copies/arc_clones reading 0 here) — the
        // collection-typed axis is a separate exploration path (#911),
        // proven to move the counters in tests/scenario_bench_model.rs
        // instead of in this checked-in matrix.
        collection_global: false,
    });
    let turn_weight_rows = [
        ("serial-100-light", TurnWeight::Light),
        ("serial-100-heavy", TurnWeight::Heavy),
    ]
    .into_iter()
    .map(|(name, turn_weight)| ScenarioConfig {
        name: name.to_string(),
        flow_count: 100,
        active_fraction: BASELINE_ACTIVE_FRACTION,
        world_size: BASELINE_WORLD_SIZE,
        turn_weight,
        frames,
        seed: BASELINE_SEED,
        collection_global: false,
    });
    flow_count_rows.chain(turn_weight_rows).collect()
}

pub fn run() -> Result<(), Box<dyn std::error::Error>> {
    let frames = parse_frames()?;
    println!("scenario_bench | frames={frames} | headless MinimalPlugins runner (issue #900)");
    println!(
        "scenario_bench | scenario | flow_count | frame_p50_ms | frame_p99_ms | turns_per_sec | rss_delta_kb"
    );

    let mut results = Vec::new();
    for config in baseline_configs(frames) {
        let r = run_scenario(&config)?;
        println!(
            "scenario_bench | {:<11} | {:>10} | {:>12.3} | {:>12.3} | {:>13.1} | {:>12}",
            r.name,
            r.flow_count,
            r.frame_p50_ms,
            r.frame_p99_ms,
            r.turns_per_sec,
            opt_i64(r.rss_delta_kb),
        );
        if r.flow_anomalies > 0 {
            println!(
                "scenario_bench | WARNING: {} flow anomalies in {} (unexpected Step outcomes — see module docs)",
                r.flow_anomalies, r.name
            );
        }
        results.push(r);
    }

    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("benches/baselines");
    fs::create_dir_all(&out_dir)?;
    write_csv(&results, &out_dir.join("serial-driver.csv"))?;
    write_markdown(&results, &out_dir.join("serial-driver.md"))?;
    println!(
        "scenario_bench | wrote {}",
        out_dir.join("serial-driver.{csv,md}").display()
    );

    Ok(())
}
